//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librurari.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookList
    {
        public int IdBook { get; set; }
        public string NameBook { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Autor { get; set; }
        public string NamePublishing { get; set; }
        public string NameReiting { get; set; }
        public int Quantity { get; set; }
        public int SizeBook { get; set; }
        public string Description { get; set; }
        public string NameGanre { get; set; }
        public decimal Prise { get; set; }
    }
}
