//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librurari.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookPikingBook = new HashSet<BookPikingBook>();
        }
    
        public int IdBook { get; set; }
        public string NameBook { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int Autor { get; set; }
        public int Publishing { get; set; }
        public int ReatengBord { get; set; }
        public int Quantity { get; set; }
        public int SizeBook { get; set; }
        public string Description { get; set; }
        public int Ganre { get; set; }
        public decimal Prise { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Autor Autor1 { get; set; }
        public virtual Ganre Ganre1 { get; set; }
        public virtual Publushing Publushing { get; set; }
        public virtual ReatengBoard ReatengBoard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookPikingBook> BookPikingBook { get; set; }
    }
}
