//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librurari.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIbrarian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIbrarian()
        {
            this.BookPiking = new HashSet<BookPiking>();
        }
    
        public int IdLibrarian { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Patronumic { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookPiking> BookPiking { get; set; }
        public virtual Gender Gender1 { get; set; }
    }
}
