//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librurari.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoReturnbook
    {
        public string NameBook { get; set; }
        public string NameSttatus { get; set; }
        public string СonditionBook { get; set; }
        public System.DateTime DateReturn { get; set; }
        public string FIO { get; set; }
    }
}
