//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librurari.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reader()
        {
            this.BookPiking = new HashSet<BookPiking>();
        }
    
        public int IdReader { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronumic { get; set; }
        public string Phone { get; set; }
        public string Addres { get; set; }
        public int Gender { get; set; }
        public Nullable<int> Pasport { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> Teg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookPiking> BookPiking { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual Pasport Pasport1 { get; set; }
        public virtual Teg Teg1 { get; set; }
    }
}
