//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librurari.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnBook
    {
        public int IdReturnBook { get; set; }
        public int StatusReturnBook { get; set; }
        public string СonditionBook { get; set; }
        public System.DateTime DateReturn { get; set; }
        public Nullable<int> IdBookPikingBook { get; set; }
    
        public virtual BookPikingBook BookPikingBook { get; set; }
        public virtual StatatusReturn StatatusReturn { get; set; }
    }
}
