//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librurari.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vivReader
    {
        public int IdReader { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronumic { get; set; }
        public string Phone { get; set; }
        public string Addres { get; set; }
        public string NameGender { get; set; }
        public string pasport { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string NameTeg { get; set; }
        public Nullable<int> QuantityBp { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
